[colors.primary]
# background = '0x1c1c1c'
# foreground = '0xbcbcbc'

[colors.normal]
black   = '0x333333'
red     = '0x8c4665'
green   = '0x287373'
yellow  = '0x7c7c99'
blue    = '0x395573'
magenta = '0x5e468c'
cyan    = '0x31658c'
white   = '0x899ca1'

[colors.bright]
black   = '0x3d3d3d'
red     = '0xbf4d80'
green   = '0x53a6a6'
yellow  = '0x9e9ecb'
blue    = '0x477ab3'
magenta = '0x7e62b3'
cyan    = '0x6096bf'
white   = '0xc0c0c0'
